USE goq1yqkgg75pzc9m;
INSERT INTO Toppings (name)
    values
    ("Bacon"),
    ("Balsamic Glaze"),
    ("Basil"),
    ("Beef Pepperoni"),
    ("Black Olives"),
    ("Blue Cheese Ranch"),
    ("Caramelized Onions"),
    ("Cheddar"),
    ("Chicken"),
    ("Chives"),
    ("Cilantro"),
    ("Corn"),
    ("Cracked Black Pepper"),
    ("Crushed Red Pepper"),
    ("Franks hot sauce"),
    ("Greek Seasoning"),
    ("Hoisin"),
    ("Jalapeños"),
    ("Lemon Pepper"),
    ("Mozzarella"),
    ("Mushroom"),
    ("Oregano"),
    ("Parmesan"),
    ("Pickled Giardiniera"),
    ("Pineapple"),
    ("Red Bell"),
    ("Red Onions"),
    ("Roasted Grape Tomatoes"),
    ("Salami"),
    ("Sausage"),
    ("Sliced Roma Tomatoes"),
    ("Spinach"),
    ("Sriracha"),
    ("Tabasco"),
    ("Teriyaki"),
    ("Valentina");
-- SELECT * FROM goq1yqkgg75pzc9m.Toppings;
